config/routes.rb
Rails.application.routes.draw do

  resources :weights, :foods , :exercises
  devise_for :users
  get "/home", to: "pages#home"
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
    belongs_to :user

end

app/models/food.rb
class Food < ApplicationRecord
    mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :weights
  has_many :exercises

end

app/models/weight.rb
class Weight < ApplicationRecord
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      home_path
    end

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :gender,:age,:image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :gender,:age,:image])
    end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = current_user.exercises
  end

  def show
    @exercise = Exercise.find_by(id: params[:id])
  end


  def new
    @exercise = Exercise.new
  end
  def create
    
  exercise_params = params.require(:exercise).permit(:name, :minute)
    @exercise = current_user.exercises.create(exercise_params)
    redirect_to @exercise
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def show
    @food = Food.find_by(id: params[:id])
  end


  def new
    @food = Food.new
  end
  def create
  food_params = params.require(:food).permit(:name, :image, :calories)
    @food = current_user.foods.create(food_params)
    redirect_to @food
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  def index
    @weights = current_user.weights
    @weight = Weight.new


  end

  def show
    @weight = Weight.find_by(id: params[:id])
    
  end

  def edit
    @weight = Weight.find_by(id: params[:id])
  end
  def update
    weight = Weight.find_by(id: params[:id])
    weight.update(weight_params)
    redirect_to weight_path(weight)
  end
  def new
    @weight = Weight.new
  end
  def destroy
    weight = Weight.find_by(id: params[:id])
    weight.destroy
    redirect_to weights_path()
  end
  def create 
    w = current_user.weights.create(weight_params)
    redirect_to weight_path(w) 
  end 
  private 
  def weight_params
    params.require(:weight).permit(:amount, :date, :comment, :user_id)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/exercises/_form.html.erb
<%= form_for @exercise do |form| %>
 Exercise: <%= form.text_field :name %>
  Minutes: <%= form.text_field :minute %>

  <%= form.submit %>
<% end %>

app/views/exercises/_nav.html.erb
<span><%= link_to "See All Exercises", exercises_path %></span>

app/views/exercises/index.html.erb
<div class="container text-large">

<%= link_to "New Exercise", new_exercise_path %>

<% @exercises.each do |exercise| %>

  <div class="card padding text-large">
<p>Exercise:<%= exercise.name %></p>
<p>Minutes:<%= exercise.minute %> Min </p>
</div>
<% end %>
</div>

app/views/exercises/new.html.erb
<div class="container">
<h1>Add a New Exercise </h1>

<%= render partial: "form" %>
</div>

app/views/exercises/show.html.erb
<div class="container">
<%= render partial: "nav" %>

<p>Exercise:<%= @exercise.name %></p>
<p>Minutes:<%= @exercise.minute %> Min</p>
</div>

app/views/foods/_form.html.erb
<%= form_for @food do |form| %>
  Name: <%= form.text_field :name %>
  Image: <%= form.file_field :image %><br>
  Calories: <%= form.text_field :calories %>
  <%= form.submit %>
<% end %>

app/views/foods/_nav.html.erb
<span><%= link_to "See All Foods", foods_path %></span>

app/views/foods/index.html.erb
<div class="container text-large">
  <div class="card padding text-large">

<%= link_to "New Food", new_food_path %>

<% @foods.each do |food| %>
  <div class="card padding text-large">

<p><%= food.name %></p>
 <img src="<%= food.image %>" alt=“image” height="300" width="500">
<p><%= food.calories %> CAL</p>
  </div>
<% end %>
</div>
</div>

app/views/foods/new.html.erb
<div class="container">
<%= render partial: "nav" %>
<h1>Add a New Meal </h1>

<%= render partial: "form" %>
</div>

app/views/foods/show.html.erb
<div class="container">
<%= render partial: "nav" %>

<p><%= @food.name %></p>
<img src="<%= @food.image %>" alt=“image” height="300" width="500">
<p><%= @food.calories %></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Compiled and minified CSS -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">



   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Compiled and minified JavaScript -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">

  </head>

  <body>
    <header>
      <%= image_tag 'logo.png', class: 'm' %>
      <nav>
        <div class="wrapper">
          <% if user_signed_in? %>
            <%= link_to "Home", root_path, class: "nav-item" %>
            <%= link_to "Edit Profile", edit_user_registration_path,class: "nav-item" %>
            <%= link_to 'Log Out', destroy_user_session_path,class: "nav-item", method: :delete %>
          <%else %>
            <%= link_to 'Log In', new_user_session_path, class: "nav-item" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-item" %>
          <%end %>
        </div>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <%= link_to image_tag("https://image.flaticon.com/icons/svg/1188/1188116.svg", border: 0), weights_path, class: 'pic1' %>
  <%= link_to image_tag("https://image.flaticon.com/icons/svg/706/706164.svg", border: 0), foods_path, class: 'pic2' %>
  <%= link_to image_tag("https://image.flaticon.com/icons/svg/1177/1177668.svg", border: 0), exercises_path, class: 'pic3' %>
   

<%#
<div class="pic">
<%=  image_tag "/assets/logo.png" %
</div>
      <a href="">
        <img class="pic2"  src="https://image.flaticon.com/icons/svg/706/706164.svg" alt="">
      </a>
      <a href="">
        <img class="pic3" src=" https://image.flaticon.com/icons/svg/1177/1177668.svg" >
      </a>
      <div class="f"> <%= link_to 'Food', foods_path </div>
      <div class="card-image ">
        <div class="w">    <%= link_to 'Weight', weights_path </span></div>
      </div>
      <div class="e"> <%= link_to 'Exercise', exercises_path %</div>
%>
<% else %>
<% end %>

app/views/weights/_form.html.erb
<div class="container">
<%= form_for @weight do |f| %>

<div>
  <%= f.label :weight %>
  <%= f.text_field :amount %>
</div>

  <div>
  <%= f.label :date %>
  <%= f.date_field :date %>
  </div>

  <div>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
  </div>

  <div>
  <%= f.submit %></div>
<% end %>
</div>

app/views/weights/edit.html.erb
<h1>Weights#edit</h1>
<p>Find me in app/views/weights/edit.html.erb</p>

app/views/weights/index.html.erb
<div class="container ">
<%= link_to "New Weight", new_weight_path %>

<% @weights.each_with_index do |weight, index| %>
  <div class="card padding text-large">
    <%= link_to weight.date, weight_path(weight) %>
    <%= weight.amount %> 
    <% previous_weight = @weights[index-1].amount unless index == 0 %>
    <% if previous_weight %>
      <% if weight.amount - previous_weight < 0 %>
        You weigh <%= (weight.amount - previous_weight).abs %> kilograms less
      <% elsif weight.amount - previous_weight == 0 %>
        Your weigh the same!
      <% else %>
        You weigh <%= (weight.amount - previous_weight).abs%> kilograms more
      <% end %>
    <% end %>
  <br>
  </div>
<% end %>
<br>
</div>

app/views/weights/new.html.erb
<%= render partial: 'form' %>

app/views/weights/show.html.erb
<div class="container">
<h1>Weights</h1>
<span><%= link_to "See All Weights", weights_path %></span>

<div>
Weight: <%= @weight.amount%> Kilos
</div>
<div>
Date: <%= @weight.date%>
</div>
<div>
Comment: <%= @weight.comment%><br>
<%= link_to 'Edit',edit_weight_path()  %>
<%= link_to "Delete ", weight_path(@weight), method: :delete %>

</div>
</div>